# Generated by Django 5.1.3 on 2024-11-18 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="City")),
                ("latitude", models.CharField(max_length=200)),
                ("longitude", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.CreateModel(
            name="WeatherRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("pressure", models.FloatField()),
                ("wind_speed", models.FloatField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[("web", "Web"), ("telegram", "Telegram")],
                        default="web",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weather",
                        to="weather_api.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weather request",
                "verbose_name_plural": "Weather requests",
            },
        ),
    ]
